import type { Metadata } from "next"
import { DM_Sans } from "next/font/google"
import "./globals.css"
import { ReactNode } from "react"

const DMSans = DM_Sans({
   variable: "--font-dm-sans",
   subsets: ["latin"],
})

export const metadata: Metadata = {
   title: "GM8",
   description: "Generated by create next app",
}

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
   return (
      <html lang="en" className={`${DMSans.variable}`}>
         <body>{children}</body>
      </html>
   )
}

export default RootLayout
