import type { Metadata } from "next"
import { DM_Sans } from "next/font/google"
import "./globals.css"
import { ReactNode } from "react"
import AppShell from "@/components/layout/AppShell"
import { OperationalProvider } from "@/components/operations/OperationalProvider"

const DMSans = DM_Sans({
   variable: "--font-dm-sans",
   subsets: ["latin"],
})

export const metadata: Metadata = {
   title: "GM8",
   description: "Generated by create next app",
}

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
   return (
      <html lang="en" className={`${DMSans.variable}`}>
         <body>
            <AppShell>
               <OperationalProvider>{children}</OperationalProvider>
            </AppShell>
         </body>
      </html>
   )
}

export default RootLayout
